# Project information
site_name: Junah
site_url: http://junah.dev
site_author: Junah Kim
site_description: Junah's personal notes
docs_dir: docs
edit_uri: ./edit/main/docs

# Repository
repo_name: junah201/junah201
repo_url: https://github.com/junah201/junah201

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

# Page tree
nav:
  - Introduction: README.md
  - Study:
      - study/README.md
      - Udemy Best React: study/udemy_best_react/README.md
      - 노마드코더 JS: study/javascript_for_beginners/readme.md
      - Eveningdev Django: study/eveningdev_django_blog/README.md
      - 생활코딩 Django: study/생활코딩_Django/README.md
      - 코드캠프 강력한 CSS: study/코드캠프_강력한_CSS/README.md
      - 노마드코드 Golang: study/go_for_beginners/README.md
  - Book:
      - book/README.md
      - Using Asyncio in Python: book/Using Asyncio in Python/README.md
      - 객체지향의 사실과 오해: book/객체지향의_사실과_오해/README.md

# Extensions
markdown_extensions:
  - mkautodoc
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Plugins
plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: long

# Copyright
copyright: Copyright &copy; 2024 Junah Kim
